import fs from 'node:fs/promises';
const tabs = await (await fetch('http://127.0.0.1:9233/json')).json();
const ws = new WebSocket(tabs.find(t => t.type === 'page').webSocketDebuggerUrl);
await new Promise(r => ws.onopen = r);
let sequence = 0;
const pending = new Map(), errors = [], results = [];
ws.onmessage = ({data}) => { const m = JSON.parse(data); if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);} if(m.method === 'Runtime.exceptionThrown') errors.push(m.params.exceptionDetails.text); };
const call = (method, params = {}) => new Promise((resolve,reject) => {const id=++sequence;pending.set(id,m => m.error ? reject(m.error) : resolve(m.result));ws.send(JSON.stringify({id,method,params}));});
const run = async expression => (await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result?.value;
const wait = () => new Promise(r => setTimeout(r,350));
const check = (name,pass) => {results.push({name,pass:!!pass}); if(!pass) process.exitCode=1;};
await call('Runtime.enable');await call('Page.enable');
await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await call('Page.navigate',{url:'http://localhost:5173'});
await new Promise(r => setTimeout(r,1900));
await run('document.fonts.ready.then(() => true)');
check('splash finishes and reveals the page',await run("getComputedStyle(document.querySelector('.splash')).visibility === 'hidden'"));
check('splash cannot block interaction or screen readers',await run("document.querySelector('.splash').inert && document.querySelector('.splash').getAttribute('aria-hidden') === 'true' && getComputedStyle(document.querySelector('.splash')).pointerEvents === 'none'"));
check('12 tools accessible without duplicate announcements',await run("document.querySelector('.tool-list:not([aria-hidden])').children.length === 12 && document.querySelectorAll('.tool-list[aria-hidden=true]').length === 1"));
const scrollBefore = await run("document.querySelector('.tool-viewport').scrollLeft");await wait();
check('carousel moves automatically',await run("document.querySelector('.tool-viewport').scrollLeft") > scrollBefore);
await run("document.querySelector('#tool-motion').click()");await wait();
const pausedScroll = await run("document.querySelector('.tool-viewport').scrollLeft");await wait();
check('pause control stops motion',await run("document.querySelector('.tool-viewport').scrollLeft") === pausedScroll);
await run("document.querySelector('#tool-motion').focus(); document.querySelector('#tool-motion').click()");
const resumeScroll = await run("document.querySelector('.tool-viewport').scrollLeft");await wait();
check('resume moves while button retains keyboard focus',await run("document.querySelector('.tool-viewport').scrollLeft") > resumeScroll);
await run("document.querySelector('.tool-viewport').focus({preventScroll:true})");await wait();
const focusScroll = await run("document.querySelector('.tool-viewport').scrollLeft");await wait();
check('focus on tool content still pauses motion',await run("document.querySelector('.tool-viewport').scrollLeft") === focusScroll);
await run("document.querySelector('#tool-motion').focus(); document.querySelector('#tool-motion').click()");
await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await wait();
check('reduced motion skips splash',await run("getComputedStyle(document.querySelector('.splash')).display === 'none'"));
check('reduced motion shows static wrapped tools',await run("getComputedStyle(document.querySelector('.tool-list')).flexWrap === 'wrap' && document.querySelector('#tool-motion').hidden && document.querySelector('.tool-list[aria-hidden]').hidden"));
await call('Emulation.setEmulatedMedia',{features:[]});await run("document.querySelector('#tool-motion').click()");
check('stylesheet linked in document head',await run("!!document.head.querySelector('link[rel=stylesheet][href*=style]')"));
check('email destination',await run("!!document.querySelector('#contact a[href=\"mailto:henok.y2014@gmail.com\"]')"));
check('phone destination',await run("!!document.querySelector('#contact a[href=\"tel:+251969124986\"]')"));
check('LinkedIn destination',await run("!!document.querySelector('#contact a[href=\"https://www.linkedin.com/in/henok-yoseph-059142210/\"]')"));
check('both promo sites linked',await run("document.querySelectorAll('.promo-link').length === 2"));
check('real app previews replace illustrations',await run("document.querySelectorAll('.phone-pair img').length === 4 && document.querySelectorAll('.illustration-label').length === 0"));
check('all eight projects rendered',await run('document.querySelectorAll(".project").length + document.querySelectorAll(".project-row").length === 8'));
check('real screenshot loaded',await run('document.querySelector(".browser-frame img").naturalWidth > 0'));
check('desktop no horizontal overflow',await run('document.documentElement.scrollWidth <= innerWidth'));
check('all supplied card screenshots load',await run("Promise.all([...document.querySelectorAll('.phone-pair img')].map(img => {img.loading = 'eager'; return img.decode().then(() => img.naturalWidth > 0).catch(() => false);})).then(results => results.every(Boolean))"));
await fs.writeFile('/tmp/henok-desktop.png',Buffer.from((await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
for (const slug of ['word-bucket','clearpath','chilluno','projecthub-bot','Chill-Anime-Vinyl','gym-landing','yt-tg-notification-bot','Channel-Sub-Manager']) {
 await run(`document.querySelector('a[href="#project/${slug}"]').focus(); document.querySelector('a[href="#project/${slug}"]').click()`);await wait();
 check(`${slug} details open`,await run('document.querySelector("dialog").open && document.querySelector("#dialog-title").textContent.length > 0'));
 check(`${slug} focus inside dialog`,await run('document.querySelector("dialog").contains(document.activeElement)'));
 await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await wait();
 check(`${slug} Escape closes`,await run('!document.querySelector("dialog").open'));
 check(`${slug} focus restored`,await run(`document.activeElement.getAttribute('href') === '#project/${slug}'`));
}
for (const width of [390,320,768]) {
 await call('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});await wait();
 check(`${width}px no horizontal overflow`,await run('document.documentElement.scrollWidth <= innerWidth'));
 if(width===390){await run('scrollTo(0,0)');await wait();await fs.writeFile('/tmp/henok-mobile.png',Buffer.from((await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));}
}
await call('Page.navigate',{url:'http://localhost:5173/#project/word-bucket'});await wait();
check('direct project link opens',await run('document.querySelector("dialog").open'));
await run('document.querySelector(".close-dialog").click()');await wait();
check('direct project link closes',await run('!document.querySelector("dialog").open'));
await call('Emulation.setScriptExecutionDisabled',{value:true});
await call('Page.navigate',{url:'http://localhost:5173/'});await new Promise(r=>setTimeout(r,900));
check('page fully styled without JavaScript',await run("getComputedStyle(document.querySelector('.header')).display === 'flex' && getComputedStyle(document.body).backgroundColor === 'rgb(8, 15, 32)'"));
await call('Emulation.setScriptExecutionDisabled',{value:false});
check('no runtime errors',errors.length===0);
console.log(JSON.stringify({results,errors},null,2));ws.close();
