import fs from 'node:fs/promises';
const tabs = await (await fetch('http://127.0.0.1:9233/json')).json();
const ws = new WebSocket(tabs.find(t => t.type === 'page').webSocketDebuggerUrl);
await new Promise(r => ws.onopen = r);
let sequence = 0;
const pending = new Map(), errors = [], results = [];
ws.onmessage = ({data}) => { const m = JSON.parse(data); if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);} if(m.method === 'Runtime.exceptionThrown') errors.push(m.params.exceptionDetails.text); };
const call = (method, params = {}) => new Promise((resolve,reject) => {const id=++sequence;pending.set(id,m => m.error ? reject(m.error) : resolve(m.result));ws.send(JSON.stringify({id,method,params}));});
const run = async expression => (await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result?.value;
const wait = () => new Promise(r => setTimeout(r,350));
const check = (name,pass) => {results.push({name,pass:!!pass}); if(!pass) process.exitCode=1;};
await call('Runtime.enable');await call('Page.enable');
await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await call('Page.navigate',{url:'http://localhost:5173'});
await new Promise(r => setTimeout(r,1900));
await run('document.fonts.ready.then(() => true)');
check('circle waits before scrolling',await run("document.querySelector('.ink-circle').classList.contains('doodle-pending') && !document.querySelector('.ink-circle').classList.contains('doodle-visible')"));
await run("document.querySelector('#writing-title').scrollIntoView({behavior:'instant',block:'center'})");await wait();
check('circle starts on entry',await run("document.querySelector('.ink-circle').classList.contains('doodle-visible') && parseFloat(getComputedStyle(document.querySelector('.ink-circle path')).strokeDashoffset) > 0"));
await new Promise(r=>setTimeout(r,1400));
check('circle finishes drawing',await run("parseFloat(getComputedStyle(document.querySelector('.ink-circle path')).strokeDashoffset) === 0"));
await run("scrollTo({top:0,behavior:'instant'})");await wait();await run("document.querySelector('#writing-title').scrollIntoView({behavior:'instant',block:'center'})");await wait();
check('circle does not replay',await run("parseFloat(getComputedStyle(document.querySelector('.ink-circle path')).strokeDashoffset) === 0"));
await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
await call('Page.navigate',{url:'http://localhost:5173/'});await new Promise(r=>setTimeout(r,700));
check('reduced motion keeps static circle',await run("!document.querySelector('.ink-circle').classList.contains('doodle-pending') && getComputedStyle(document.querySelector('.ink-circle path')).animationName === 'none'"));
await call('Emulation.setEmulatedMedia',{features:[]});
check('no runtime errors',errors.length===0);
console.log(JSON.stringify({results,errors},null,2));ws.close();
